# docker.io/library is used for compatibility with podman

services:

  attacker:
    container_name: attacker
    hostname: attacker
    image: gitlab.fi.muni.cz:5050/cybersec/infra/images/kali/kali:main
    restart: on-failure
    volumes:
      - ./student_home/root:/root
      - user-data:/home
      - ./student_home/xuser/shared:/home/xuser/shared
    tty: true
    cap_add:
      - NET_ADMIN # for capturing packages in promiscuous mode
      - NET_RAW # for raw sockets e.g. used for the boreas alive detection
      - SYS_ADMIN # for ability to mount volumes
      - DAC_READ_SEARCH # for ability to mount volmues
    ports:
      - "127.0.0.1:14000:13389" # only local access
      # - "14000:13389" # DEBUG ONLY: remote access
    networks:
      vnet:
        ipv4_address: 10.0.0.254

  dvwa:
    # image: ghcr.io/digininja/dvwa:0a509bd
    # image: ghcr.io/digininja/dvwa:latest
    image: gitlab.fi.muni.cz:5050/cybersec/infra/images/dvwa/dvwa:main
    environment:
      - DB_SERVER=db
      # - DISABLE_AUTHENTICATION=true # does not work, must be changed in config/config.inc.php
      - DEFAULT_SECURITY_LEVEL=low
    depends_on:
      - db
    networks:
      vnet:
        ipv4_address: 10.0.0.10
    ports:
      - 127.0.0.1:4280:80
    restart: unless-stopped
    cap_add:
      - NET_ADMIN # for capturing packages in promiscuous mode
      - NET_RAW # for raw sockets e.g. used for the boreas alive detection
      - SYS_ADMIN # for ability to mount volumes
      - DAC_READ_SEARCH # for ability to mount volmues

  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - vnet
    restart: unless-stopped

networks:
  vnet:
    name: vnet
    ipam:
      config:
        - subnet: 10.0.0.0/16

volumes:
  user-data:
  dvwa:
